/**
 * default app roles
 */
export const defaultRoles = [
  {
    type: 'superAdmin',
    name: 'Super Admin',
    permissions: [
      'view_startups',
      'load_all_startups',
      'create_startups',
      'edit_startups',
      'view_experts',
      'create_experts',
      'edit_experts',
      'view_entrepreneurs',
      'load_all_entrepreneurs',
      'create_entrepreneurs',
      'edit_entrepreneurs',
      'view_business',
      'create_business',
      'edit_business',
      'download_all_tables',
      'reports_view',
      'reports_create',
      'reports_edit',
      'community_view',
      'community_create',
      'community_edit',
      'form_view',
      'form_create',
      'form_edit',
      'help_desk_view',
      'help_desk_create',
      'help_desk_edit',
      'sites_and_services_view',
      'sites_and_services_create',
      'sites_and_services_edit',
      'announcements_view',
      'announcements_challenges',
      'announcements_edit_challenge',
      'announcements_create',
      'announcements_edit',
      'phases_batch_access',
      'phases_phase_access',
      'phases_phase_edit',
      'phases_batch_create',
      'phases_batch_edit',
      'phases_batch_close',
      'events_view',
      'load_all_events',
      'events_create',
      'events_edit',
      'actas_view',
      'actas_create',
      'actas_edit',
      'actas_close',
      'hours_view',
      'hours_edit_activities',
      'hours_edit_startups',
      'hours_edit_experts',
      'hours_edit_teamCoach',
      'evaluation_view',
      'evaluation_create',
      'evaluation_edit',
      'evaluation_edit_docs',
      'homeworks_view',
      'homeworks_evaluate',
    ],
  },
  {
    type: 'admin',
    name: 'Administrador',
    permissions: [
      'view_startups',
      'load_all_startups',
      'create_startups',
      'edit_startups',
      'view_experts',
      'create_experts',
      'edit_experts',
      'view_entrepreneurs',
      'load_all_entrepreneurs',
      'create_entrepreneurs',
      'edit_entrepreneurs',
      'view_business',
      'create_business',
      'edit_business',
      'download_all_tables',
      'reports_view',
      'reports_create',
      'reports_edit',
      'community_view',
      'community_create',
      'community_edit',
      'form_view',
      'form_create',
      'form_edit',
      'help_desk_view',
      'help_desk_create',
      'help_desk_edit',
      'sites_and_services_view',
      'sites_and_services_create',
      'sites_and_services_edit',
      'announcements_view',
      'announcements_challenges',
      'announcements_edit_challenge',
      'announcements_create',
      'announcements_edit',
      'phases_batch_access',
      'phases_phase_access',
      'phases_phase_edit',
      'phases_batch_create',
      'phases_batch_edit',
      'phases_batch_close',
      'events_view',
      'load_all_events',
      'events_create',
      'events_edit',
      'actas_view',
      'actas_create',
      'actas_edit',
      'actas_close',
      'hours_view',
      'hours_edit_activities',
      'hours_edit_startups',
      'hours_edit_experts',
      'hours_edit_teamCoach',
      'evaluation_view',
      'evaluation_create',
      'evaluation_edit',
      'evaluation_edit_docs',
      'homeworks_view',
      'homeworks_evaluate',
    ],
  },
  {
    type: 'host',
    name: 'Host',
    permissions: [
      'view_startups',
      'load_all_startups',
      'create_startups',
      'edit_startups',
      'view_experts',
      'create_experts',
      'edit_experts',
      'view_entrepreneurs',
      'load_all_entrepreneurs',
      'create_entrepreneurs',
      'edit_entrepreneurs',
      'download_all_tables',
      'reports_view',
      'reports_create',
      'reports_edit',
      'sites_and_services_view',
      'phases_batch_access',
      'events_view',
      'load_all_events',
      'events_create',
      'events_edit',
      'actas_view',
      'actas_create',
      'actas_edit',
      'actas_close',
      'hours_view',
      'hours_edit_activities',
      'hours_edit_startups',
      'hours_edit_experts',
      'hours_edit_teamCoach',
      'evaluation_view',
      'evaluation_create',
      'evaluation_edit',
      'evaluation_edit_docs',
      'homeworks_view',
      'homeworks_evaluate',
    ],
  },
  {
    type: 'teamCoach',
    name: 'Team Coach',
    permissions: [
      'view_startups',
      'view_entrepreneurs',
      'community_view',
      'phases_batch_access',
      'events_view',
      'events_create',
      'events_edit',
      'actas_view',
      'actas_create',
      'actas_edit',
      'actas_close',
      'evaluation_view',
      'evaluation_create',
      'evaluation_edit',
      'evaluation_edit_docs',
    ],
  },
  {
    type: 'expert',
    name: 'Experto',
    permissions: [
      'view_startups',
      'view_entrepreneurs',
      'phases_batch_access',
      'actas_view',
      'actas_view',
      'actas_create',
      'actas_edit',
      'actas_close',
      'events_view',
      'events_create',
      'events_edit',
      'evaluation_view',
      'evaluation_create',
      'evaluation_edit',
      'evaluation_edit_docs',
    ],
  },
  {
    type: 'user',
    name: 'Usuario',
    permissions: [],
  },
  {
    type: 'challenger',
    name: 'Challenger',
    permissions: [],
  },
];
/**
 * permission list
 */
export const listPermission = {
  // Startups
  view_startups: true,
  create_startups: true,
  edit_startups: true,

  // Experts
  view_experts: true,
  create_experts: true,
  edit_experts: true,

  // Entrepreneurs
  view_entrepreneurs: true,
  create_entrepreneurs: true,
  edit_entrepreneurs: true,

  // Business
  view_business: true,
  create_business: true,
  edit_business: true,

  // Tables
  download_all_tables: true,

  // Reports
  reports_view: true,
  reports_create: true,
  reports_edit: true,

  // Community
  community_view: true,
  community_create: true,
  community_edit: true,

  // Forms
  form_view: true,
  form_create: true,
  form_edit: true,

  // Help Desk
  help_desk_view: true,
  help_desk_create: true,
  help_desk_edit: true,

  // Sites
  sites_and_services_view: true,
  sites_and_services_create: true,
  sites_and_services_edit: true,

  // Announcements
  announcements_view: true,
  announcements_challenges: true,
  announcements_create: true,
  announcements_edit: true,

  // Phase and batch
  phases_view: true,
  phases_batch_create: true,
  phases_batch_access: true,
  phases_batch_edit: true,
  phases_batch_content: true,
  phases_phase_edit: true,

  // Phase Events
  events_view: true,
  events_create: true,
  events_edit: true,

  // Phase Actas
  actas_view: true,
  actas_create: true,
  actas_close: true,
  actas_edit: true,

  // Phase Hours bag
  hours_view: true,
  hours_edit_activities: true,
  hours_edit_startups: true,
  hours_edit_experts: true,
};
